apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# 배포할 리소스에 공통 라벨 적용
commonLabels:
  part-of: k8s-anotherclass
  component: backend-server
  name: api-tester
  instance: api-tester-2222
  managed-by: kustomize
# 배포할 리소스 선택
resources:
  - configmap.yaml
  - deployment.yaml
  - secret.yaml
  - service.yaml